#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""批量将 Capability 返回给 AI 的错误文案替换为中文。"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
CAP_ROOT = ROOT / "nexus-unreal/Plugins/Developer/NexusLink/Source/NexusLink/Private"

# 精确匹配 TEXT("...") 静态字符串
EXACT: dict[str, str] = {
    "Missing assetPath": "缺少 assetPath",
    "Missing parameters": "缺少参数",
    "Invalid arguments": "参数无效",
    "Missing command": "缺少 command",
    "Missing actorName": "缺少 actorName",
    "Missing address": "缺少 address",
    "Missing assetPath or skeletonPath": "缺少 assetPath 或 skeletonPath",
    "Missing required parameter: action": "缺少必填参数 action",
    "Missing required parameter: assetPath": "缺少必填参数 assetPath",
    "Missing action": "缺少 action",
    "Actor not found": "Actor 未找到",
    "Invalid update item": "无效的 update 项",
    "Invalid field item": "无效的 field 项",
    "Invalid widget item": "无效的 widget 项",
    "Invalid key item": "无效的 key 项",
    "Invalid op item": "无效的 op 项",
    "Invalid operation item": "无效的操作项",
    "Invalid Blueprint target": "无效的 Blueprint 目标",
    "Invalid WidgetBlueprint target": "无效的 WidgetBlueprint 目标",
    "Invalid AnimBlueprint target": "无效的 AnimBlueprint 目标",
    "Invalid AnimInstance target": "无效的 AnimInstance 目标",
    "Invalid hexadecimal address": "无效的十六进制地址",
    "Invalid material target": "无效的材质目标",
    "No active World": "无活动 World",
    "No running PIE session": "无运行中的 PIE 会话",
    "PIE already running; call stop first": "PIE 已在运行；请先 stop",
    "control_pie is only available in editor mode": "control_pie 仅在编辑器模式可用",
    "Button is disabled": "Button 已禁用",
    "package global is not available": "package 全局表不可用",
    "package.loaded is not available": "package.loaded 不可用",
    "action is required": "缺少 action",
    "assetPath is required": "assetPath 为必填项",
    "updates is required": "缺少 updates",
    "propertyPath is required": "缺少 propertyPath",
    "propertyPath is empty": "propertyPath 为空",
    "propertyPath is required for each update": "每项 update 均须 propertyPath",
    "actorName is required": "缺少 actorName",
    "widgetName is required": "缺少 widgetName",
    "widgetName is required when action=remove": "action=remove 时 widgetName 必填",
    "widgetClass is required when action=add": "action=add 时 widgetClass 必填",
    "newPath is required": "缺少 newPath",
    "set action requires value": "set 操作需要 value",
    "Failed to create package": "创建包失败",
    "Failed to create SCS node": "创建 SCS 节点失败",
    "Failed to get CDO": "获取 CDO 失败",
    "Blueprint has no SimpleConstructionScript": "Blueprint 无 SimpleConstructionScript",
    "Blueprint has no generated class": "Blueprint 无生成类",
    "DataTable has no row struct": "DataTable 无行结构体",
    "Node not found": "节点未找到",
    "Target node not found": "目标节点未找到",
    "Source node not found": "源节点未找到",
    "Source pin not found": "源引脚未找到",
    "Variable already exists": "变量已存在",
    "Variable not found (or is inherited)": "变量未找到（或为继承变量）",
    "WidgetTree is empty": "WidgetTree 为空",
    "WidgetTree unavailable": "WidgetTree 不可用",
    "WidgetBlueprint creation failed": "WidgetBlueprint 创建失败",
    "GEditor unavailable": "GEditor 不可用",
    "GEngine unavailable": "GEngine 不可用",
    "save_asset is only available in editor mode": "save_asset 仅在编辑器模式可用",
    "actor section requires actorName": "actor 段需要 actorName",
    "asset section requires assetPath": "asset 段需要 assetPath",
    "actorNameA and actorNameB are required": "需要 actorNameA 与 actorNameB",
    "assetPath must point to a Blueprint asset": "assetPath 须指向 Blueprint 资产",
    "blueprintPath or className is required": "需要 blueprintPath 或 className",
    "categories is required (array of strings)": "缺少 categories（字符串数组）",
    "componentName is required": "缺少 componentName",
    "componentName is required for remove_component": "remove_component 需要 componentName",
    "connect requires targetNodeId and targetPinName": "connect 需要 targetNodeId 与 targetPinName",
    "disconnect requires targetNodeId and targetPinName": "disconnect 需要 targetNodeId 与 targetPinName",
    "sourceNodeId and sourcePinName are required for wire actions": "连线操作需要 sourceNodeId 与 sourcePinName",
    "fields is required": "缺少 fields",
    "fields must be non-empty": "fields 不能为空",
    "functionName is required for K2Node_CallFunction": "K2Node_CallFunction 需要 functionName",
    "keys is required": "缺少 keys",
    "mode=rows requires non-empty rowNames": "mode=rows 需要非空 rowNames",
    "nodeId is required for remove_node": "remove_node 需要 nodeId",
    "nodeId is required for set_node": "set_node 需要 nodeId",
    "operations is required": "缺少 operations",
    "operations must be non-empty": "operations 不能为空",
    "ops is required": "缺少 ops",
    "ops must be non-empty": "ops 不能为空",
    "rows is required": "缺少 rows",
    "rows must be non-empty": "rows 不能为空",
    "widgets is required": "缺少 widgets",
    "widgets must be non-empty": "widgets 不能为空",
    "widgetName and action are required": "需要 widgetName 与 action",
    "section=graph applies only to Material or MaterialFunction, not MaterialInstance": "section=graph 仅适用于 Material/MaterialFunction，不适用 MaterialInstance",
    "Actor has no AnimInstance (no SkeletalMeshComponent or animation not initialized)": "Actor 无 AnimInstance（无 SkeletalMeshComponent 或动画未初始化）",
    "BlackboardData creation failed": "BlackboardData 创建失败",
    "Tool has no Execute implementation": "工具未实现 Execute",
    "PlayerController not found": "PlayerController 未找到",
    "CreateWidget failed": "CreateWidget 失败",
    "AIController not found": "AIController 未找到",
    "BlackboardData not found for the given path": "给定路径的 BlackboardData 未找到",
    "Struct creation failed": "Struct 创建失败",
    "BehaviorTree creation failed": "BehaviorTree 创建失败",
    "AnimBlueprint creation failed": "AnimBlueprint 创建失败",
    "AnimMontage creation failed": "AnimMontage 创建失败",
    "DataTable creation failed": "DataTable 创建失败",
    "Failed to create BehaviorTree package": "创建 BehaviorTree 包失败",
    "Failed to remove field": "删除字段失败",
    "Failed to add field": "添加字段失败",
    "fieldType is required when action=add": "action=add 时 fieldType 必填",
    "propertyName is required": "propertyName 必填",
    "fieldName is required for set": "set 操作需要 fieldName",
    "rowName is required": "rowName 必填",
    "'value' is required": "缺少 value",
    "sectionName is required for remove_section": "remove_section 需要 sectionName",
    "ConnectMaterialProperty failed": "ConnectMaterialProperty 失败",
    "ConnectMaterialExpressions failed": "ConnectMaterialExpressions 失败",
    "variableName is required": "variableName 必填",
    "variableType is required for add_variable": "add_variable 需要 variableType",
    "componentClass is required for add_component": "add_component 需要 componentClass",
    "componentName is required for add_component": "add_component 需要 componentName",
    "propertyPath is required for set_defaults": "set_defaults 需要 propertyPath",
    "stateMachineName is required for add_state_machine": "add_state_machine 需要 stateMachineName",
    "Failed to create state machine sub-graph": "创建状态机子图失败",
    "stateMachineName is required for remove_state_machine": "remove_state_machine 需要 stateMachineName",
    "stateMachineName is required for add_state": "add_state 需要 stateMachineName",
    "stateName is required for add_state": "add_state 需要 stateName",
    "stateMachineName is required for remove_state": "remove_state 需要 stateMachineName",
    "stateName is required for remove_state": "remove_state 需要 stateName",
    "stateMachineName is required for add_transition": "add_transition 需要 stateMachineName",
    "stateName (source) is required for add_transition": "add_transition 需要 stateName（源）",
    "targetStateName is required for add_transition": "add_transition 需要 targetStateName",
    "Actor specified by actorNameA not found": "actorNameA 指定的 Actor 未找到",
    "Actor specified by actorNameB not found": "actorNameB 指定的 Actor 未找到",
    "viewAngle is only available in editor mode": "viewAngle 仅在编辑器模式可用",
    "PIE start requested; it will actually start next frame.": "已请求启动 PIE；将在下一帧实际开始。",
    "PIE stop requested.": "已请求停止 PIE。",
    "Use list_runtime_widgets to enumerate widgets and interact_widget to operate them": "用 list_runtime_widgets 枚举 Widget，用 interact_runtime_widget 操作",
    "graphName is required for node/wire actions. Hint: call get_asset_blueprint(sections=[\"graphOverview\"]) first to list graph names.": "节点/连线操作需要 graphName。提示：先 get_asset_blueprint(sections=[\"graphOverview\"]) 列出图名。",
    # capture_viewport
    "PIE viewport capture failed": "PIE 视口截图失败",
    "Editor viewport tab not found": "未找到编辑器视口标签页",
    "Editor viewport capture is only available in editor mode": "编辑器视口截图仅在编辑器模式可用",
    "Target editor window not found. Note: minimized windows cannot be captured; restore the window and retry.": "未找到目标编辑器窗口。最小化窗口无法截图，请恢复窗口后重试。",
    "Editor window capture failed (FWidgetRenderer)": "编辑器窗口截图失败（FWidgetRenderer）",
    "Panel capture is only available in editor mode": "面板截图仅在编辑器模式可用",
    # behavior_tree
    "nodeClass is required for set_root": "set_root 需要 nodeClass",
    "nodeClass is required for add_decorator": "add_decorator 需要 nodeClass",
    "nodeClass is required for add_service": "add_service 需要 nodeClass",
    "targetPath is required for remove_node; use set_root to replace the root": "remove_node 需要 targetPath；用 set_root 替换根节点",
    "blackboardPath is required for set_blackboard": "set_blackboard 需要 blackboardPath",
    "propertyName is required for set_property": "set_property 需要 propertyName",
    "propertyValue is required for set_property": "set_property 需要 propertyValue",
    # blackboard
    "keyName is required for this action": "此操作需要 keyName",
    "keyType is required when action=add": "action=add 时 keyType 必填",
    "newName is required when action=rename": "action=rename 时 newName 必填",
    "Cannot set self as parent": "不能将自身设为父级",
    # anim_blueprint remove_transition
    "stateMachineName is required for remove_transition": "remove_transition 需要 stateMachineName",
    "stateName (source) is required for remove_transition": "remove_transition 需要 stateName（源）",
    "targetStateName is required for remove_transition": "remove_transition 需要 targetStateName",
    # data_asset / data_table / struct / material
    "DataAsset creation failed": "DataAsset 创建失败",
    "Missing required parameter 'parentMaterial' for MaterialInstance creation.": "创建 MaterialInstance 缺少必填参数 parentMaterial。",
    "Missing required parameters: assetPath, rowStructName": "缺少必填参数: assetPath, rowStructName",
    "assetPath and rowStructName must be non-empty": "assetPath 与 rowStructName 不能为空",
    "Invalid row item": "无效的行项",
    "action and rowName are required": "action 与 rowName 必填",
    "action and fieldName are required": "action 与 fieldName 必填",
    # lua / runtime
    "value only supports string / number / boolean / null": "value 仅支持 string/number/boolean/null",
    "Component itself cannot be assigned; specify a sub-property": "不能直接赋值组件本身，请指定子属性",
    "UnLua module is registered but .lua file is missing on disk; check Content/Script path or create the file.": "UnLua 模块已注册但磁盘缺少 .lua 文件；请检查 Content/Script 路径或创建文件。",
    "Cannot resolve Lua table for object (neither instance nor class table is available)": "无法解析对象的 Lua 表（实例表与类表均不可用）",
}

# Printf 格式串（保留 %s 等占位符）
PRINTF: dict[str, str] = {
    "Missing required field '%s' for capability '%s'": "缺少必填字段 '%s'（Capability '%s'）",
    "Missing or empty required field '%s'": "缺少或为空必填字段 '%s'",
    "Asset not found: %s": "资产未找到: %s",
    "Actor not found: %s": "Actor 未找到: %s",
    "Unsupported action: '%s'": "不支持的操作: '%s'",
    "Unsupported section '%s'": "不支持的 section '%s'",
    "Unsupported widget type: %s": "不支持的 Widget 类型: %s",
    "Unsupported mode: %s (expected: collect / stop / restart / count)": "不支持的 mode: %s（期望 collect/stop/restart/count）",
    "Invalid mode '%s' (auto|schema|rows)": "无效的 mode '%s'（auto|schema|rows）",
    "Invalid direction '%s'; expected 'dependencies' or 'referencers'": "无效的 direction '%s'；期望 dependencies 或 referencers",
    "Invalid assetPath: %s": "无效的 assetPath: %s",
    "Invalid newPath: %s": "无效的 newPath: %s",
    "Invalid package path '%s': %s": "无效的包路径 '%s': %s",
    "Invalid parent class (not a UObject subclass): %s": "无效的父类（非 UObject 子类）: %s",
    "Missing required parameters: assetPath, parentClass": "缺少必填参数: assetPath, parentClass",
    "File does not exist: %s": "文件不存在: %s",
    "Unhandled section '%s'": "未处理的 section '%s'",
    "Unknown section '%s' (supported: %s)": "未知 section '%s'（支持: %s）",
    "Runtime widget '%s' not found": "运行时 Widget '%s' 未找到",
    "No running World (call control_pie start first)": "无运行中的 World（请先 control_pie start）",
    "Path '%s' not found": "路径 '%s' 未找到",
    "BehaviorTree not found: %s": "BehaviorTree 未找到: %s",
    "BlackboardData not found: %s": "BlackboardData 未找到: %s",
    "AnimBlueprint not found: %s": "AnimBlueprint 未找到: %s",
    "AnimMontage not found: %s": "AnimMontage 未找到: %s",
    "WidgetBlueprint not found: %s": "WidgetBlueprint 未找到: %s",
    "DataTable not found: %s": "DataTable 未找到: %s",
    "Target already exists: %s": "目标已存在: %s",
    "Failed to load Skeleton: %s": "加载 Skeleton 失败: %s",
    "Failed to create package: %s": "创建包失败: %s",
    "Target pin '%s' not found": "目标引脚 '%s' 未找到",
    "Component '%s' not found": "组件 '%s' 未找到",
    "State machine '%s' not found": "状态机 '%s' 未找到",
    "Key '%s' not found in user-defined keys": "用户定义键中未找到 '%s'",
    "Row '%s' does not exist": "行 '%s' 不存在",
    "Field not found: %s": "字段未找到: %s",
    "Property '%s' not found on %s": "在 %s 上未找到属性 '%s'",
    "nodeClass is required for add_node": "add_node 需要 nodeClass",
    "Asset is not a DataAsset: %s": "资产不是 DataAsset: %s",
    "ImportText failed for field '%s'": "字段 '%s' ImportText 失败",
    "One or more fields could not be applied": "部分字段未能应用",
    "Editor viewport capture failed": "编辑器视口截图失败",
    "Widget '%s' not found": "Widget '%s' 未找到",
    "Button does not support action=%s": "Button 不支持 action=%s",
    "Slider does not support action=%s": "Slider 不支持 action=%s",
    "EditableTextBox does not support action=%s": "EditableTextBox 不支持 action=%s",
    "EditableText does not support action=%s": "EditableText 不支持 action=%s",
    "Destroy failed: %s": "销毁失败: %s",
    "Asset already exists: %s": "资产已存在: %s",
    "Asset is not a Blueprint: %s": "资产不是 Blueprint: %s",
    "Asset is not a Material, MaterialInstance, or MaterialFunction: %s": "资产不是 Material/MaterialInstance/MaterialFunction: %s",
    "Asset is not a UserDefinedStruct: %s": "资产不是 UserDefinedStruct: %s",
    "Blueprint not found: %s": "Blueprint 未找到: %s",
    "Graph '%s' not found. Available: %s": "Graph '%s' 未找到。可用: %s",
    "Parent class not found: %s": "父类未找到: %s",
    "%s is not a subclass of UserWidget": "%s 不是 UserWidget 子类",
    "UserWidget class not found: %s": "UserWidget 类未找到: %s",
    "Widget not found: %s": "Widget 未找到: %s",
    "Widget class not found: %s": "Widget 类未找到: %s",
    "Failed to create widget: %s": "创建 Widget 失败: %s",
    "Parent panel widget not found: %s": "父面板 Widget 未找到: %s",
    "UserDefinedStruct not found: %s": "UserDefinedStruct 未找到: %s",
    "Struct already exists: %s": "Struct 已存在: %s",
    "Blueprint not found or not compiled: %s": "Blueprint 未找到或未编译: %s",
    "Actor class not found: %s": "Actor 类未找到: %s",
    "Actor spawn failed (class: %s)": "Actor 生成失败（类: %s）",
    "Panel '%s' capture failed": "面板 '%s' 截图失败",
    "Runtime UMG widget not found: %s": "运行时 UMG Widget 未找到: %s",
    "Widget '%s' has no screen geometry (likely invisible)": "Widget '%s' 无屏幕几何（可能不可见）",
    "Tag not found: '%s'": "标签未找到: '%s'",
    "BlackboardData already exists: %s": "BlackboardData 已存在: %s",
    "AnimBlueprint already exists: %s": "AnimBlueprint 已存在: %s",
    "AnimSequence not found: %s": "AnimSequence 未找到: %s",
    "AnimSequence path is required for add_segment": "add_segment 需要 AnimSequence 路径",
    "Slot '%s' not found": "槽位 '%s' 未找到",
    "segmentIndex is required for remove_segment": "remove_segment 需要 segmentIndex",
    "segmentIndex %d out of range [0, %d)": "segmentIndex %d 超出范围 [0, %d)",
    "sectionName is required for add_section": "add_section 需要 sectionName",
    "Section '%s' already exists": "分段 '%s' 已存在",
    "Cannot connect: %s": "无法连接: %s",
    "Component '%s' already exists": "组件 '%s' 已存在",
    "Component class not found or not an ActorComponent: %s": "组件类未找到或不是 ActorComponent: %s",
    "attachTo component '%s' not found": "attachTo 组件 '%s' 未找到",
    "Function '%s' not found (tried 'K2_%s')": "函数 '%s' 未找到（已尝试 'K2_%s'）",
    "Node class '%s' not found": "节点类 '%s' 未找到",
    "Node class '%s' does not support defaultValue": "节点类 '%s' 不支持 defaultValue",
    "Pin '%s' not found": "引脚 '%s' 未找到",
    "Unknown action '%s'": "未知 action '%s'",
    "%s requires variableName": "%s 需要 variableName",
    "%s (package not found)": "%s（包未找到）",
    "%s (path conversion failed)": "%s（路径转换失败）",
    "%s (SavePackage failed)": "%s（SavePackage 失败）",
    "Rename failed: %s -> %s": "重命名失败: %s -> %s",
    "Duplicate failed: %s -> %s": "复制失败: %s -> %s",
    "Vector defaultValue requires 'R,G,B' or 'R,G,B,A', got: %s": "Vector defaultValue 需要 'R,G,B' 或 'R,G,B,A'，实际: %s",
    "vector value requires 'R,G,B' or 'R,G,B,A', got: %s": "vector 值需要 'R,G,B' 或 'R,G,B,A'，实际: %s",
    "Texture not found: %s": "纹理未找到: %s",
    "Unknown paramType: %s": "未知 paramType: %s",
    "Expression class not found: %s": "表达式类未找到: %s",
    "Failed to create expression: %s": "创建表达式失败: %s",
    "Expression not found: %s": "表达式未找到: %s",
    "Source expression not found: %s": "源表达式未找到: %s",
    "Target expression not found: %s": "目标表达式未找到: %s",
    "Unknown material property: %s": "未知材质属性: %s",
    "parameterName not applicable to '%s'": "parameterName 不适用于 '%s'",
    "Failed to set '%s' = '%s'": "设置 '%s' = '%s' 失败",
    "'%s' is not a table": "'%s' 不是 table",
    "Lua load error: %s": "Lua 加载错误: %s",
    "Lua exec error: %s": "Lua 执行错误: %s",
    "Unknown diagnose preset: '%s' (supported: visibility / transform / world_transform / rotation_chain / defaults)": "未知 diagnose 预设: '%s'（支持: visibility/transform/world_transform/rotation_chain/defaults）",
    " (did you mean view='%s'?)": "（是否指 view='%s'？）",
    "Unknown view: '%s' (supported: components / attach_hierarchy / all)": "未知 view: '%s'（支持: components/attach_hierarchy/all）",
    " (did you mean diagnose='%s'?)": "（是否指 diagnose='%s'？）",
    "Capability '%s' is disabled in settings.": "Capability '%s' 已在设置中禁用。",
    "Tool not found: %s": "工具未找到: %s",
    "Method not found: %s": "方法未找到: %s",
    "Parse error": "JSON 解析错误",
    "Invalid JSON-RPC version": "无效的 JSON-RPC 版本",
    "Missing method": "缺少 method",
    "Session not initialized": "会话未初始化",
    "Missing params": "缺少 params",
    "Missing tool name": "缺少工具名",
    "Failed to create tool instance": "创建工具实例失败",
    "Request body is empty": "请求体为空",
    "Invalid or missing Mcp-Session-Id": "无效或缺少 Mcp-Session-Id",
    "Blueprint creation failed: %s": "Blueprint 创建失败: %s",
    "%s (asset not found)": "%s（资产未找到）",
    "%s (delete failed, possibly referenced)": "%s（删除失败，可能被引用）",
    "Row struct not found: %s": "行结构体未找到: %s",
    "Property '%s' not found in class %s": "属性 '%s' 在类 %s 中未找到",
    "ImportText failed for '%s'": "ImportText 失败: '%s'",
    "Section '%s' not found": "分段 '%s' 未找到",
    "Input pin '%s' not found on node '%s'": "节点 '%2$s' 上未找到输入引脚 '%1$s'",
    "Output pin '%s' not found on node '%s'": "节点 '%2$s' 上未找到输出引脚 '%1$s'",
    "Parent material not found: %s": "父材质未找到: %s",
    "Failed to create MaterialInstance at %s": "在 %s 创建 MaterialInstance 失败",
    "Failed to create Material at %s": "在 %s 创建 Material 失败",
    "AnimGraph '%s' not found in AnimBlueprint": "AnimBlueprint 中未找到 AnimGraph '%s'",
    "State '%s' not found in '%s'": "在 '%2$s' 中未找到状态 '%1$s'",
    "Source '%s' or target '%s' state not found": "源状态 '%1$s' 或目标状态 '%2$s' 未找到",
    "Graph '%s' not found. Hint: graphName is the graph object name, not a function name. Available: %s": "Graph '%s' 未找到。提示：graphName 是图对象名而非函数名。可用: %s",
    "nodeClass '%s' not found": "nodeClass '%s' 未找到",
    "nodeClass '%s' not found or not a BTCompositeNode subclass": "nodeClass '%s' 未找到或不是 BTCompositeNode 子类",
    "nodeClass '%s' not found or not a BTDecorator subclass": "nodeClass '%s' 未找到或不是 BTDecorator 子类",
    "nodeClass '%s' not found or not a BTService subclass": "nodeClass '%s' 未找到或不是 BTService 子类",
    "nodeClass '%s' must be a BTCompositeNode or BTTaskNode subclass": "nodeClass '%s' 须为 BTCompositeNode 或 BTTaskNode 子类",
    "Node not found at targetPath '%s'": "targetPath '%s' 处未找到节点",
    "parentPath '%s' not found": "parentPath '%s' 未找到",
    "Failed to set '%s' = '%s' (ImportText failed)": "设置 '%s' = '%s' 失败（ImportText 失败）",
    "targetPath '%s' is invalid": "targetPath '%s' 无效",
    "Transition '%s' -> '%s' not found": "过渡 '%s' -> '%s' 未找到",
    "Parent BlackboardData not found: %s": "父 BlackboardData 未找到: %s",
    "DataAsset subclass not found: %s": "DataAsset 子类未找到: %s",
    "Panel '%s' not found; call with target='list' to see available panels": "面板 '%s' 未找到；用 target='list' 查看可用面板",
    "Actor '%s' is outside the viewport or projection failed": "Actor '%s' 在视口外或投影失败",
    "Path '%s' not found (nil or a mid node is not a table)": "路径 '%s' 未找到（nil 或中间节点不是 table）",
    "Lua parse error: %s": "Lua 解析错误: %s",
    "Lua eval error: %s": "Lua 求值错误: %s",
    "Invalid type '%s' (Material|MaterialInstance)": "无效 type '%s'（Material|MaterialInstance）",
    "Unsupported JSON type for field '%s' (use string/number/bool/null)": "字段 '%s' 不支持的 JSON 类型（请用 string/number/bool/null）",
    "'%s' is not a table; cannot set a sub-field": "'%s' 不是 table，无法设置子字段",
    "Blueprint parent is not an Actor subclass: %s (parent=%s). Hint: add_component/set_defaults require Actor BP; use add_variable/add_node for GameplayAbility/UI BPs.": "Blueprint 父类不是 Actor 子类: %s（parent=%s）。提示：add_component/set_defaults 需要 Actor BP；GameplayAbility/UI BP 请用 add_variable/add_node。",
    "Class %s is abstract and cannot be instantiated directly. Use a non-abstract UDataAsset subclass (e.g. a Blueprint child of PrimaryDataAsset) as parentClass.": "类 %s 为抽象类，无法直接实例化。请使用非抽象 UDataAsset 子类（如 PrimaryDataAsset 的 Blueprint 子类）作为 parentClass。",
}


def _cpp_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _replace_text_literals(text: str, en: str, zh: str) -> tuple[str, int]:
    n = 0
    pairs = [(en, zh)]
    esc_en = _cpp_escape(en)
    if esc_en != en:
        pairs.append((esc_en, _cpp_escape(zh)))
    for en_raw, zh_raw in pairs:
        old = f'TEXT("{en_raw}")'
        new = f'TEXT("{zh_raw}")'
        if old in text:
            c = text.count(old)
            text = text.replace(old, new)
            n += c
    return text, n


def process(text: str) -> tuple[str, int]:
    n = 0
    for en, zh in EXACT.items():
        text, c = _replace_text_literals(text, en, zh)
        n += c
    for en, zh in PRINTF.items():
        text, c = _replace_text_literals(text, en, zh)
        n += c
    return text, n


def main() -> int:
    total = 0
    paths = list((CAP_ROOT / "Capabilities").rglob("*.cpp"))
    paths.append(CAP_ROOT / "NexusCapability.cpp")
    paths.append(CAP_ROOT / "NexusMcpTool.cpp")
    for sub in ("Tools", "Server"):
        d = CAP_ROOT / sub
        if d.is_dir():
            paths.extend(d.rglob("*.cpp"))
    for p in sorted(paths):
        orig = p.read_text(encoding="utf-8")
        new, n = process(orig)
        if n:
            p.write_text(new, encoding="utf-8")
            print(f"{p.name}: {n}")
            total += n
    print(f"\nTotal: {total}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
